### ISSUE TITLE
Promise error when connectionStatus is equal to 1 

### ISSUE THREAD

**Issue by thibremy** [fortunejs/fortune#184]
This [gist](https://gist.github.com/thibremy/1954cd0910863f36dfa0) doesn't work.
On `Fortune.prototype.request` when connectionStatus is equal to 1 I have this error

```
TypeError: Promise is not a function
    at [object Object].Fortune.request (/Users/thibremy/Documents/WWW/contrackor/contrackor-api/node_modules/fortune/lib/core.js:317:12)
    at find (fortune.promise.js:11:24)
```

PR: #183

**Comment by 0x8890** [comment]
PR has been merged.
