### ISSUE TITLE
Allow Nested, Recursive Model

### ISSUE THREAD

**Issue by srsgores** [fortunejs/fortune#187]
We would like to have a model which references itself:

```
module.exports = {
	user: {
		name: {type: String},
		desires: {
			link: "desire",
			isArray: true
		}
	},
	desire: {
		title: {type: String},
		text: {type: String},
		createdAt: {type: Date},
		updatedAt: {type: Date},
		coordinates: {type: Object},
		followers: {
			link: "user",
			isArray: true
		},
		desires: {
			link: "desire",
			isArray: true
		}
	}
};
```

But this returns the following errors:

> Unhandled rejection (<{"payload":{"type":"Buffer","data":[31...>, no stack trace)
	Unhandled rejection NotFoundError: The requested type "favicon.ico" is not a valid type.
		at c:\Users\seang\Documents\Github\app\node_modules\fortune\lib\dispatch\index.js:56:13
	at tryCatcher (c:\Users\seang\Documents\Github\app\node_modules\bluebird\js\release\util.js:16:23)
	at Promise._settlePromiseFromHandler (c:\Users\seang\Documents\Github\app\node_modules\bluebird\js\release\promise.js:503:31)
	at Promise._settlePromise (c:\Users\seang\Documents\Github\app\node_modules\bluebird\js\release\promise.js:560:18)
	at Promise._settlePromiseCtx (c:\Users\seang\Documents\Github\app\node_modules\bluebird\js\release\promise.js:597:10)
	at Async._drainQueue (c:\Users\seang\Documents\Github\app\node_modules\bluebird\js\release\async.js:131:12)
	at Async._drainQueues (c:\Users\seang\Documents\Github\app\node_modules\bluebird\js\release\async.js:136:10)
	at Immediate.Async.drainQueues [as _onImmediate] (c:\Users\seang\Documents\Github\app\node_modules\bluebird\js\release\async.js:16:14)
	at processImmediate [as _immediateCallback] (timers.js:383:17)

**Comment by 0x8890** [comment]
There's no problem with your data model. Read the first line of the stack trace:

```
Unhandled rejection NotFoundError: The requested type "favicon.ico" is not a valid type.
```

Looks like a web browser is trying to find something that doesn't exist.

**Comment by srsgores** [comment]
@0x8890, would I not have to specify `inverse` in this case?

**Comment by 0x8890** [comment]
@srsgores generally you should, but it's not required. If you do not specify `inverse`, Fortune will automatically create an inverse field named like `__${type}__${field}__inverse`, which is reserved for internal use and not exposed to clients.
