### ISSUE TITLE
Errors on http requests with default setup

### ISSUE THREAD

**Issue by voronianski** [fortunejs/fortune#194]
I'm trying to build an api on top of express and fortune, for now it's basic setup with mongodb-adapter and one store, the source code is available here - https://github.com/dhhb/api-next

In my entry file I'm using fortune as express middleware on `/v1` routes:

```js
// src/index.js
import http from 'http';
import cors from 'cors';
import logger from 'morgan';
import express from 'express';
import { host, port, env } from 'c0nfig';
import v1 from './v1';

const app = express();

if ('test' !== env) {
    app.use(logger('dev'));
}

app.use(cors());
app.use('/v1', v1());

http.createServer(app).listen(port, () => {
    console.log(`api is listening on http://${host}:${port} env=${env}`);
});
```

```js
// src/v1/index.js
import express from 'express';
import fortune from 'fortune';
import store from './store';

export default function () {
    const router = express.Router();
    const listener = fortune.net.http(store);

    router.use(listener);

    return router;
}
```

The store just requires types (in this example it's only one `user` type) and creates fortune instance:

```js
// src/v1/store.js
import fortune from 'fortune';
import mongodbAdapter from 'fortune-mongodb';
import { mongo } from 'c0nfig';
import * as types from './types';

const recordTypes = {};
const transforms = {};
Object.keys(types).forEach(key => {
    const t = types[key];
    recordTypes[t.name] = t.definition;
    transforms[t.name] = [t.input, t.output];
});

const adapter = [
    mongodbAdapter,
    {url: mongo.connection}
];

const store = fortune(recordTypes, adapter, transforms);

export default store;
```

**The app starts successfully however there are strange errors when I try to work with api itself, I need your input on them:**

1) When I make GET request to `http://localhost:9876/v1` it returns json:

```json
{
  "recordTypes": ["user"]
}
```
but in console I see such red error:

```bash
GET /v1/ 200 4.299 ms - 53
Unhandled rejection (<{"payload":{"type":"Buffer","data":[31...>, no stack trace)
```

What's wrong here?

2) When I make GET request to `http://localhost:9876/v1/user` it returns json:
```json
{
  "records": [],
  "count": 0
}
```

but when I'm trying to create a new user with POST `http://localhost:9876/v1/user` (I'm sending `application/json` data with the same types as in https://github.com/dhhb/api-next/blob/master/src/v1/types/user.js#L4), it returns error:

```json
{
  "name": "BadRequestError",
  "message": "There are no valid records to be created."
}
```
and in console:

```bash
POST /v1/user/ 400 41.645 ms - 101
Unhandled rejection BadRequestError: There are no valid records to be created.
    at /Users/dmitri/github/dhhb/api-fortune/node_modules/fortune/lib/dispatch/create.js:53:13
    at tryCatcher (/Users/dmitri/github/dhhb/api-fortune/node_modules/fortune/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/dmitri/github/dhhb/api-fortune/node_modules/fortune/node_modules/bluebird/js/release/promise.js:503:31)
    at Promise._settlePromise (/Users/dmitri/github/dhhb/api-fortune/node_modules/fortune/node_modules/bluebird/js/release/promise.js:560:18)
    at Promise._settlePromiseCtx (/Users/dmitri/github/dhhb/api-fortune/node_modules/fortune/node_modules/bluebird/js/release/promise.js:597:10)
    at Async._drainQueue (/Users/dmitri/github/dhhb/api-fortune/node_modules/fortune/node_modules/bluebird/js/release/async.js:131:12)
    at Async._drainQueues (/Users/dmitri/github/dhhb/api-fortune/node_modules/fortune/node_modules/bluebird/js/release/async.js:136:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/dmitri/github/dhhb/api-fortune/node_modules/fortune/node_modules/bluebird/js/release/async.js:16:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

What I'm missing? Is serializer required?

**Comment by 0x8890** [comment]
1) it's my fault, an implementation detail that wasn't fully considered. I reject the promise prematurely so that it doesn't make a database request, but this should be implemented better. however it is safe to ignore. will fix.

2) right now it's necessary to wrap the record in an array, like `[ { ... } ]`. this restriction should be loosened, will fix.

**Comment by voronianski** [comment]
@0x8890 thanks, I fixed configuration and figured out of records as array in code. :+1: 

I also would like to know is it ok that fortune throws errors in console like:

```bash
GET /v1/fdfd 404 69.669 ms - 103
Unhandled rejection NotFoundError: The requested type "fdfd" is not a valid type.
    at /Users/dmitri/github/dhhb/api-fortune/node_modules/fortune/lib/dispatch/index.js:56:13
    at tryCatcher (/Users/dmitri/github/dhhb/api-fortune/node_modules/fortune/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/dmitri/github/dhhb/api-fortune/node_modules/fortune/node_modules/bluebird/js/release/promise.js:503:31)
    at Promise._settlePromise (/Users/dmitri/github/dhhb/api-fortune/node_modules/fortune/node_modules/bluebird/js/release/promise.js:560:18)
    at Promise._settlePromiseCtx (/Users/dmitri/github/dhhb/api-fortune/node_modules/fortune/node_modules/bluebird/js/release/promise.js:597:10)
    at Async._drainQueue (/Users/dmitri/github/dhhb/api-fortune/node_modules/fortune/node_modules/bluebird/js/release/async.js:131:12)
    at Async._drainQueues (/Users/dmitri/github/dhhb/api-fortune/node_modules/fortune/node_modules/bluebird/js/release/async.js:136:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/dmitri/github/dhhb/api-fortune/node_modules/fortune/node_modules/bluebird/js/release/async.js:16:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

**Comment by 0x8890** [comment]
@voronianski yes, that is intended. if it is too noisy, you can catch the promise from the listener yourself :)

I pushed a patch release in this commit: https://github.com/fortunejs/fortune/commit/469054deccaa9d2c5bc77cfa89fb561ade36cc02

**Comment by voronianski** [comment]
@0x8890 thanks a lot! you're fast :)

**Comment by voronianski** [comment]
@0x8890 also I would like to know your opinion, regarding login/signup endpoints. 

- should I use POST `/user` endpoint as signup and for `/login` declare my own via express routes and handle login by myself?

- what is the proper way to validate payload against schema (e.g. ensure that `"email"` string is email format etc), is it in input transform function?

Thanks!

**Comment by 0x8890** [comment]
- why not create a `token` or `session` type, which you would `POST` to, in order to get login credentials?
- input transform is for any sort of business logic, so yes.

**Comment by voronianski** [comment]
@0x8890 that makes sense, thanks again!
