### ISSUE TITLE
The proper way of handling file uploads

### ISSUE THREAD

**Issue by voronianski** [fortunejs/fortune#195]
In my application I have several cases where I need to upload images for fortune recordTypes. For example, I have `user` type which has `picture` field:

```js
const user = {
    name: 'user',

    collection: 'users',

    definition: {
        name: {
            type: String
        },
        email: {
            type: Email
        },
        picture: {
            type: String
        },
        role: {
            type: Enum('writer|admin')
        }
    },
//...
}
```

_souce: https://github.com/dhhb/api-next/blob/master/src/v1/types/user.js#L7_

I'm thinking about several options:

- ideally I would like to send image as form-data and upload it to S3, and then save link to image in bucket in user `picture` field. However this doesn't look simple to achieve via fortune. I have POST `/users` endpoint and it accepts json as payload.

- with this in mind I was thinking about just sending image in `picture` field as base64 in json payload and then save it to S3.

What do you think will be the best way?

**Comment by 0x8890** [comment]
There is a `multipart/formdata` serializer that is included by default, if you need to use forms for binary uploading. See [an example here](https://github.com/0x8890/imagenote/blob/master/lib/serializers/form-data.js).

In the input transform, you could then upload to S3, and actually store `null` for the image buffer and also store the link to the image.

**Comment by voronianski** [comment]
@0x8890 I included form-data serializer like:

```js
import jsonApiSerializer from 'fortune-json-api';
import store from './store';

const formDataSerializer = fortune.net.http.FormDataSerializer;

const listener = fortune.net.http(store, {
    serializers: [
        [ jsonApiSerializer ],
        [ formDataSerializer ]
    ]
});

//...
```

But when I'm doing form-data request POST `/users` I'm getting such error in console:

```bash
POST /v1/user/ 400 36.793 ms - 1158
BadRequestError: Invalid JSON: Unexpected number
    at JsonApiSerializer.parseBuffer (/Users/dmitri/github/dhhb/api-fortune/node_modules/fortune-json-api/lib/helpers.js:398:11)
    at JsonApiSerializer.parseCreate (/Users/dmitri/github/dhhb/api-fortune/node_modules/fortune-json-api/lib/index.js:312:42)
    at JsonApiSerializer.parsePayload (/Users/dmitri/github/dhhb/api-fortune/node_modules/fortune-json-api/lib/index.js:304:48)
    at /Users/dmitri/github/dhhb/api-fortune/node_modules/fortune/lib/net/http_server.js:229:40
    at tryCatcher (/Users/dmitri/github/dhhb/api-fortune/node_modules/fortune/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/dmitri/github/dhhb/api-fortune/node_modules/fortune/node_modules/bluebird/js/release/promise.js:503:31)
    at Promise._settlePromise (/Users/dmitri/github/dhhb/api-fortune/node_modules/fortune/node_modules/bluebird/js/release/promise.js:560:18)
    at Promise._settlePromiseCtx (/Users/dmitri/github/dhhb/api-fortune/node_modules/fortune/node_modules/bluebird/js/release/promise.js:597:10)
    at Async._drainQueue (/Users/dmitri/github/dhhb/api-fortune/node_modules/fortune/node_modules/bluebird/js/release/async.js:131:12)
    at Async._drainQueues (/Users/dmitri/github/dhhb/api-fortune/node_modules/fortune/node_modules/bluebird/js/release/async.js:136:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/dmitri/github/dhhb/api-fortune/node_modules/fortune/node_modules/bluebird/js/release/async.js:16:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

**Comment by 0x8890** [comment]
Did you make the request from a web browser using a file input? If not, it's not so simple to generate a formdata request. For starters, at least the `Content-Type` header of the request must be `multipart/form-data`.

**Comment by voronianski** [comment]
@0x8890 yes, it was my fault with `Content-Type` which was set by me, btw I'm using Postman desktop client. Thanks!

Now I see the Buffer data inside input function and will figure out how to properly store it. 

The main thing that I saw in your example is that you differentiate `imageLink` and `imageData` and both fields should be present on type, right?

**Comment by 0x8890** [comment]
Yes, like I said above, the same field can't be either a buffer or a string.

**Comment by voronianski** [comment]
@0x8890 thanks!
