### ISSUE TITLE
Stability issue 

### ISSUE THREAD

**Issue by thomasthiebaud** [fortunejs/fortune#241]
Hej, I came throw a stability issue during the day. I don't know if this issue is from fortune or from the test framework. I am using this models

```
const user = {
    email: String,
    password: String,
    phone: String,
    avatar: String,
    role: String,
    customer: ['customer', 'users'],
};

const customer = {
    name: String,
    address: String,
    apikey: String,
    role: String,
    users: [Array('user'), 'customer'],
};

const adapter = [
    postgresAdapter, {
        url: `postgres://${config.get('DATABASE_USER')}:${config.get('DATABASE_PASSWORD')}@${config.get('DATABASE_HOST')}:${5432}/${config.get('DATABASE_NAME')}`,
        useForeignKeys: true,
        generatePrimaryKey: () => uuid.v4(),
    },
];

const store = fortune({
    // Put models here
    customer,
    user,
}, {
    adapter,
});
```

and `mocha` as a test framework. In my tests, the `beforeEach` hook cleans tables and inserts some data.

```
describe('/customers', function () {
  beforeEach(function () {
    return Promise.all([store.delete('customer'), store.delete('user')])
      .then(() => store.create('customer', {
        id: '0987654321234567890',
        name: 'Combain',
        address: 'Scheelevägen 15, 223 63 Lund',
        apikey: '01234567899876543210',
        role: 'admin',
      }))
      .then(() => store.create('user', {
        id: 'qwertyuioppoiuytrewq',
        customer: '0987654321234567890',
        email: 'demo@combain.com',
        password: 'demo',
        phone: 'demo',
        avatar: 'demo',
        role: 'admin',
      }));
  });

  describe('#GET', function () {
    it('should get all customers', function (done) {
      done();
    })
  });

  describe('Title 1', function () {
    it('name 1', function (done) {
      done();
    })
  });

  describe('Title "', function () {
    it('name 2', function (done) {
      done();
    })
  });

  describe('Title 3', function () {
    it('name 3', function (done) {
      done();
    })
  });
});
```

The first test is always working, but the second and third (and the others one) are not stable : they are working sometime (around 50%). I get this error from the `beforeEach` hook and as far as I understand the message, `fortune` is trying to reference a customer that does not exist.

> BadRequestError: A related record for the field "customer" was not found.
    at node_modules/fortune/lib/dispatch/check_links.js:59:29
    at process._tickCallback (internal/process/next_tick.js:103:7)

I debugged it, an the customer is here (and in the database). And the tests are working sometimes. I'm thinking on a problem on the promises returned by `fortune`. Do you think it is a bug ?

**Comment by thomasthiebaud** [comment]
The problem is not related to fortunejs but to `Promise.all`. See this [thread](http://stackoverflow.com/questions/39677248/is-promise-all-equivalent-to-promise-then-then/39677295?noredirect=1#comment66654959_39677295) for more details
