### ISSUE TITLE
Error and hooks are not called

### ISSUE THREAD

**Issue by voronianski** [fortunejs/fortune#266]
Also related to my migration from v3 to v5:

my hooks methods are not called at all and I have such error:

```
TypeError: Cannot use 'in' operator to search for 'type' in undefined
    at data.map.record (/Users/voronianski/github/api-next/node_modules/fortune-json-api/lib/index.js:415:36)
    at Array.map (native)
    at JsonApiSerializer.parseCreate (/Users/voronianski/github/api-next/node_modules/fortune-json-api/lib/index.js:414:19)
    at JsonApiSerializer.parsePayload (/Users/voronianski/github/api-next/node_modules/fortune-json-api/lib/index.js:372:21)
    at /Users/voronianski/github/api-next/node_modules/fortune-http/lib/index.js:220:14
    at process._tickDomainCallback (internal/process/next_tick.js:129:7)
```

**Comment by voronianski** [comment]
@daliwali this is example of hooks:

- https://github.com/dhhb/api-next/blob/master/src/v1/types/user.js#L48

and this how I init fortune:

- https://github.com/dhhb/api-next/blob/master/src/v1/store.js

**Comment by voronianski** [comment]
@daliwali sorry, long time without touching this project and forgot about JSON API spec.
