### ISSUE TITLE
Empty update.replace object returns database error

### ISSUE THREAD

**Issue by voronianski** [fortunejs/fortune#267]
Empty `update.replace` object returns db error (mongo in my case). Is it by design?

```bash
MongoError: '$set' is empty. You must specify a field like so: {$set: {<field>: ...}}
    at Function.MongoError.create (/Users/dmitri/github/dhhb/api-next/node_modules/mongodb-core/lib/error.js:31:11)
    at toError (/Users/dmitri/github/dhhb/api-next/node_modules/mongodb/lib/utils.js:114:22)
    at /Users/dmitri/github/dhhb/api-next/node_modules/mongodb/lib/collection.js:1049:67
    at /Users/dmitri/github/dhhb/api-next/node_modules/mongodb-core/lib/connection/pool.js:455:18
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
```

**Comment by daliwali** [comment]
Seems like an unintended side effect, probably a bug in the MongoDB adapter.

**Comment by daliwali** [comment]
After a bit more thought, I decided that this should be fixed in the adapter, since other adapters have no problems with this. https://github.com/fortunejs/fortune-mongodb/commit/32e1439a83b1e020074ee97f52168e13d25633d0
