### ISSUE TITLE
Assert "Cannot call method 'forEach' of undefined"

### ISSUE THREAD

**Issue by vabatta** [fortunejs/fortune#58]
Hello,

while using this software with an empty repo, copied your basic example with these dependencies:
```json
"dependencies": {
    "fortune": "^0.2.4",
    "fortune-mongodb": "^0.2.2"
  }
```
app.js
```js
var fortune = require('fortune')
  , app = fortune({
    adapter: 'mongodb',
    db: 'petstore'
  })
  .resource('person', {
    name: String,
    age: Number,
    pets: ['pet'] // "has many" relationship to pets
  })
  .resource('pet', {
    name: String,
    age: Number,
    owner: 'person' // "belongs to" relationship to a person
  })
  .listen(1337);
```

I'm trying to creating a resource, with this json:
```json
{"pets": 
  {
    "name": "Dog",
    "age": 18
  }
}
```

The response is the following a 400 with this:
```json
{
  "error": "Request was malformed.",
  "detail": "TypeError: Object #<Object> has no method 'forEach'"
}
```

And this is the trace on console:
```txt
Trace: [TypeError: Cannot call method 'forEach' of undefined]
    at sendError (/Users/<user>/Projects/PetExample/node_modules/fortune/lib/route.js:43:26)
    at createResources (/Users/<user>/Projects/PetExample/node_modules/fortune/lib/route.js:238:16)
    at /Users/<user>/Projects/PetExample/node_modules/fortune/lib/route.js:136:5
    at Layer.handle [as handle_request] (/Users/<user>/Projects/PetExample/node_modules/fortune/node_modules/express/lib/router/layer.js:76:5)
    at next (/Users/<user>/Projects/PetExample/node_modules/fortune/node_modules/express/lib/router/route.js:100:13)
    at Route.dispatch (/Users/<user>/Projects/PetExample/node_modules/fortune/node_modules/express/lib/router/route.js:81:3)
    at Layer.handle [as handle_request] (/Users/<user>/Projects/PetExample/node_modules/fortune/node_modules/express/lib/router/layer.js:76:5)
    at /Users/<user>/Projects/PetExample/node_modules/fortune/node_modules/express/lib/router/index.js:227:24
    at Function.proto.process_params (/Users/<user>/Projects/PetExample/node_modules/fortune/node_modules/express/lib/router/index.js:305:12)
    at /Users/<user>/Projects/PetExample/node_modules/fortune/node_modules/express/lib/router/index.js:221:12
TypeError: Cannot call method 'then' of undefined
    at /Users/<user>/Projects/PetExample/node_modules/fortune/lib/route.js:139:6
    at Layer.handle [as handle_request] (/Users/<user>/Projects/PetExample/node_modules/fortune/node_modules/express/lib/router/layer.js:76:5)
    at next (/Users/<user>/Projects/PetExample/node_modules/fortune/node_modules/express/lib/router/route.js:100:13)
    at Route.dispatch (/Users/<user>/Projects/PetExample/node_modules/fortune/node_modules/express/lib/router/route.js:81:3)
    at Layer.handle [as handle_request] (/Users/<user>/Projects/PetExample/node_modules/fortune/node_modules/express/lib/router/layer.js:76:5)
    at /Users/<user>/Projects/PetExample/node_modules/fortune/node_modules/express/lib/router/index.js:227:24
    at Function.proto.process_params (/Users/<user>/Projects/PetExample/node_modules/fortune/node_modules/express/lib/router/index.js:305:12)
    at /Users/<user>/Projects/PetExample/node_modules/fortune/node_modules/express/lib/router/index.js:221:12
    at Function.match_layer (/Users/<user>/Projects/PetExample/node_modules/fortune/node_modules/express/lib/router/index.js:288:3)
    at next (/Users/<user>/Projects/PetExample/node_modules/fortune/node_modules/express/lib/router/index.js:182:10)
```

What's I'm doing wrong?

**Comment by ferdegje** [comment]
@vabatta did you find a solution to this issue? I'm facing the same and cannot figure out what I am doing wrong.

**Comment by daliwali** [comment]
@ferdegje The solution is to wait until `1.0.0-alpha.1` is released ;)

If you haven't noticed, the `master` branch has been stagnant for a while since I'm working on the `rewrite` branch. I should make the notice in the readme bigger, or just hurry up and ship 1.0 alpha.

**Comment by ferdegje** [comment]
@vabatta found the solution to your issue, the body of your request is wrong.

You send:
{"pets": 
  {
    "name": "Dog",
    "age": 18
  }
}

But you should send:
{"pets": 
[
  {
    "name": "Dog",
    "age": 18
  }
]
}

Otherwise it will create the issue you have documented

**Comment by vabatta** [comment]
@ferdegje as reported on [json api](http://jsonapi.org/format/), you could have an array of resource objects or just a single object rapresenting the model. Fortunejs respond always with an array, and this cause the error.
I fixed just proxing everything to an array, adding this after `lib/route.js#L232`:
```js
if (typeof resources !== Array) resources = [resources];
```
